name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: npm run lint

  deploy:
    name: Deploy to DO
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm install -g gatsby-cli
      - run: gatsby build
      - name: Upload repo to DO
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
          ssh -o StrictHostKeyChecking=no aps@${{ secrets.HOST }} "rm -rf ${{ secrets.DESTINATION }}/public"
          scp -o StrictHostKeyChecking=no -r public aps@${{ secrets.HOST }}:${{ secrets.DESTINATION }}
